new revision 8.56.0: 	* include all changes from 8.56 GPL release from Artifex software 	* add NEWS and AUTHORS files

diff --git a/lib/ps2epsi b/lib/ps2epsi
--- a/lib/ps2epsi
+++ b/lib/ps2epsi
@@ -1,11 +1,18 @@
 #!/bin/sh
-# $Id: ps2epsi,v 1.5 2006/06/16 18:54:58 Arabidopsis Exp $
+# $Id: ps2epsi,v 1.6 2007/05/07 11:22:07 Arabidopsis Exp $
 
 # This definition is changed on install to match the
 # executable name set in the makefile
 GS_EXECUTABLE=gs
 
-tmpfile=/tmp/ps2epsi$$
+# try to create a temporary file securely
+tmpdir=/tmp/ps2epsi.$$
+(umask 077 && mkdir $tmpdir)
+if test ! -d $tmpdir; then
+	echo "failed: could not create temporary file"
+	exit 1
+fi
+tmpfile=$tmpdir/ps2epsi$$
 
 export outfile
 
