2007/09/11 Didier LINK <didier@famille-link.fr>: 	* Update to version 8.60.0 from the GPL release

diff --git a/lib/ps2epsi b/lib/ps2epsi
--- a/lib/ps2epsi
+++ b/lib/ps2epsi
@@ -1,18 +1,31 @@
 #!/bin/sh
-# $Id: ps2epsi,v 1.6 2007/05/07 11:22:07 Arabidopsis Exp $
+# $Id: ps2epsi,v 1.7 2007/09/11 15:24:50 Arabidopsis Exp $
 
 # This definition is changed on install to match the
 # executable name set in the makefile
 GS_EXECUTABLE=gs
+gs="`dirname $0`/$GS_EXECUTABLE"
+if test ! -x "$gs"; then
+	gs="$GS_EXECUTABLE"
+fi
+GS_EXECUTABLE="$gs"
 
 # try to create a temporary file securely
-tmpdir=/tmp/ps2epsi.$$
-(umask 077 && mkdir $tmpdir)
-if test ! -d $tmpdir; then
-	echo "failed: could not create temporary file"
-	exit 1
+if test -z "$TMPDIR"; then
+	TMPDIR=/tmp
 fi
-tmpfile=$tmpdir/ps2epsi$$
+if which mktemp >/dev/null 2>/dev/null; then
+	tmpfile="`mktemp $TMPDIR/ps2epsi.XXXXXX`"
+else
+	tmpdir=$TMPDIR/ps2epsi.$$
+	(umask 077 && mkdir "$tmpdir")
+	if test ! -d "$tmpdir"; then
+		echo "failed: could not create temporary file"
+		exit 1
+	fi
+	tmpfile="$tmpdir"/ps2epsi$$
+fi
+trap "rm -rf \"$tmpfile\"" 0 1 2 3 7 13 15
 
 export outfile
 
@@ -60,11 +73,11 @@ awk 'F==1	{
 		print "end";
 		exit(0);
 		}
-	' U="$USERNAME$LOGNAME"  F=1 - F=2 "${infile}" >$tmpfile
+	' U="$USERNAME$LOGNAME"  F=1 - F=2 "${infile}" >"$tmpfile"
 
-$GS_EXECUTABLE -q -dNOPAUSE -dSAFER -dDELAYSAFER -r72 -sDEVICE=bit -sOutputFile=/dev/null $tmpfile ps2epsi.ps $tmpfile <"${infile}" 1>&2
-rm -f $tmpfile
-rm -rf $tmpdir
+"$GS_EXECUTABLE" -q -dNOPAUSE -dSAFER -dDELAYSAFER -r72 -sDEVICE=bit -sOutputFile=/dev/null "$tmpfile" ps2epsi.ps "$tmpfile" <"${infile}" 1>&2
+rm -f "$tmpfile"
+rm -rf "$tmpdir"
 
 (
 cat << BEGINEPS
@@ -74,6 +87,7 @@ save countdictstack mark newpath /showpage {} def /setpagedevice {pop} def
 BEGINEPS
 
 cat "${infile}" |
+LC_ALL=C \
 sed -e '/^%%BeginPreview:/,/^%%EndPreview[^!-\~]*$/d' -e '/^%!PS-Adobe/d'\
 	-e '/^%%[A-Za-z][A-Za-z]*[^!-\~]*$/d' -e '/^%%[A-Za-z][A-Za-z]*: /d'
 
